#!/usr/bin/env node
/* eslint no-undef: 0 */

(function main() {
  const fs = require('fs')
  const glob = require('glob')
  const autocorrect = require('autocorrect-node')

  let config = { verbose: false, filepath: null }

  let args = process.argv.slice(2)
  if (args.includes('--verbose')) {
    config.verbose = true
    args = args.filter(arg => arg !== '--verbose')
  }
  if (args.length === 1) config.filepath = args[0]
  else if (args.length > 1) return console.error('Too many arguments!')
  else return console.error('No filepath specified!')

  const files = glob.sync(config.filepath)
  const logPrefix = '[AutoCorrect]'

  let changedCount = 0
  files.forEach(file => {
    config.verbose && console.log(`${logPrefix} Processing file: ${file}`)
    const fileContent = fs.readFileSync(file, 'utf8')
    const corrected = autocorrect.formatFor(fileContent, file.split('.').pop())
    if (corrected !== fileContent) changedCount += 1
    fs.writeFileSync(file, corrected, 'utf8')
  })

  console.log(`${logPrefix} Processed ${files.length} files, ${changedCount} changed.`)
}())
